# Use an official Node.js runtime as a parent image
FROM node:14.16.0-alpine

# Set the working directory to /app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# Copy package.json and package-lock.json to the container
COPY package*.json ./
COPY .env ./.env
# Install dependencies
RUN npm install

# Copy the rest of the app's code to the container
COPY . .

# Build the app
RUN npm run build

# Set the command to start the app
CMD ["npm", "start"]
